### ISSUE TITLE
Problem mit ReWrite-URL for Gallery

### ISSUE THREAD

**Issue by AlexL777** [webguerilla/joomla-gallery#3]
Hello developers,
I have just installed the gallery component and have created a new menu item. In the frontend there is then a new link /galerie. Unfortunately, nothing is behind this link appears and it leads only to route.

Do I need to maybe adjust something? I use PHP 5.5 and have in my Joomla 3 blog search engine friendly URLs. When I have created the new menu link "alias" nothing entered in the field. The system made it by himself /galerie.

Can you help me maybe? Thank you in advance!

**Comment by webguerilla** [comment]
Hi Alex,

sorry for my late reply. I somehow overlooked your question and forgot to answer earlier. I think your request is not current anymore, or is it? :-)

Best regards,
Marco

**Comment by AlexL777** [comment]
Hi Marco,
but I still have questions and I do not know how I can fill the gallery with pictures.

In the options is that you have to create a directory on the server and upload pictures there. Is that right?! But what URL has the gallery in the frontend? For me it is http://internetblogger.de/gallery, but behind it is nothing and I have no rights.

I have on the server creates the directory /gallery and uploaded all the pictures, but it is not working.

The directory has 777 and is equal to the root directory. You have the menu item the alias of the gallery and I specify it in "gallery". I do not get along with it and if you can help me that way. Thank you in advance.

**Comment by webguerilla** [comment]
Hi Alex,

Yes, that's right. You have to create a menu item, where you define the folder. Typically a subfolder of the 'images' folder. For example 'images/gallery' is the default. Then you will upload your photos in the 'images/gallery' folder.

If I understand you right, you have put the 'gallery' folder in the root of your Joomla installation and also created a menu item with the alias 'gallery'. This may cause the error. The request tries to access the folder directly and not the linked menu item. You should move the photo folder somewhere else. A subdirectory of the images folder would be a good choice and then it should normally work.

By the way, I've published some new versions with lots of bug fixes since your request. You could update to the latest version if not already done.

Best regards,
Marco

**Comment by AlexL777** [comment]
Hello Marco,
now it has now worked. I did it wrong, but then I instead "Galeries" only one "Gallery" behind /images/gallery taken. So it worked.

But thank you for your time and help. Cool and interesting it would be if you could comment on the images. Perhaps that would be a new feature for you in the future :)

**Comment by webguerilla** [comment]
Hello Alex,

Thank you for your feedback, that's nice.

I have currently not planned a comment feature, maybe in the future. But you don't have to wait for it, if you really need it. The gallery is currently not my main project and so the development of new features is relatively slow.

If you like, you could open a new issue for the comment feature. Then you could easily stay up to date if I'm going to implement it.

Best regards,
Marco
